spring.application.name=backend
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/safelab?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Creará las tablas automáticamente basándose en las entidades de Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.naming.physical-strategy=com.test.backend.shared.infrastructure.persistence.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# ===================================================================
# MQTT HiveMQ Configuration
# ===================================================================
mqtt.host=${MQTT_HOST}
mqtt.port=${MQTT_PORT}
mqtt.protocol=${MQTT_PROTOCOL}
mqtt.username=${MQTT_USER}
mqtt.password=${MQTT_PASSWORD}
mqtt.topic=safelab/#