# ===================================================================
# Production Database Configuration (Se llena desde Render)
# ===================================================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# ===================================================================
# MQTT HiveMQ Cloud Configuration (Prod)
# ===================================================================
mqtt.host=3ede04f10be549b69b46ad698994b1f6.s1.eu.hivemq.cloud
mqtt.port=8883
mqtt.protocol=mqtts
mqtt.username=${MQTT_USER}
mqtt.password=${MQTT_PASSWORD}

# ===================================================================
# JWT Configuration
# ===================================================================
authorization.jwt.secret=${JWT_SECRET}
