# ===================================================================
# Production Database Configuration (Se llena desde Render)
# ===================================================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Limit connection pool size due to MySQL limit of 5 concurrent connections
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}


# ===================================================================
# MQTT HiveMQ Cloud Configuration (Prod)
# ===================================================================
mqtt.host=${MQTT_HOST}
mqtt.port=8883
mqtt.protocol=mqtts

mqtt.username=${MQTT_USER}
mqtt.password=${MQTT_PASSWORD}

# ===================================================================
# JWT Configuration
# ===================================================================
authorization.jwt.secret=${JWT_SECRET}

